{{- if .Values.ingress.search }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: search-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ quote .Values.os2display.general.certmanagerIssuer }}
spec:
  rules:
    - host: {{ quote .Values.os2display.search.publicDomain }}
      http:
        paths:
          - backend:
              serviceName: search
              servicePort: main-port
            path: /
  tls:
    - hosts:
        - {{ quote .Values.os2display.search.publicDomain }}
      secretName: search-ingress-cert # cert-manager will populate this.
{{- end }}
