# What to expose, you normally just want all of these enabled for cloud 
# environments. Could be disabled in local environments without Ingress-
# controllers.
ingress:
  admin: true
  screen: true
  search: true

# Docker image configuration
images:
  adminRelease:
    image: reload/os2display-admin-release
    tag: reload-build-1
  adminPhp:
    image: reload/os2display-admin-php
    tag: reload-1.1.0
  adminNginx:
    image: reload/os2display-admin-nginx
    tag: reload-0.1.0
  screen:
    image: reload/os2display-screen
    tag: 5.0.3-reload-0.1.1
  search:
    image: reload/os2display-search
    tag: 2.1.10-docker-compatibility-2-reload-0.1.0
  middleware:
    image: reload/os2display-middleware
    tag: 5.0.2-console-json-logging-2-reload-0.1.0
  elasticsearch:
    image: reload/os2display-elasticsearch
    tag: 1.7.1-reload-0.1.0
  redis:
    image: reload/os2display-redis
    tag: 4.0.9-reload-0.1.0

# Application configuration
os2display:
  general:
    certmanagerIssuer: "letsencrypt-prod"
    # Mainly used for generating the site-title for the admin-backend.
    environmentName: ""

  admin:
    mailerFromEmail: "admin@example.com"
    mailerFromName: "OS2Display Admin"
    secret: "<insert-random-string-here>"
    publicDomain: "admin.example.com"
    publicUrl: "https://admin.example.com"

  search:
    publicUrl: "https://search.example.com"
    secret: "<insert-random-string-here>"
    searchApikey: "searchapikey"
    searchIndex: "mainsearchindex"
    username: "admin"
    password: "<insert-admin-password-here>"
    publicDomain: "search.example.com"

  middleware:
    mainApiKey: "middleware-main-api-key"
    secret: "<insert-random-string-here>"
    username: "admin"
    password: "<insert-admin-password-here>"

  screen:
      publicDomain: "screen.example.com"
      publicUrl: "https://screen.example.com"


